ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS manufacturer TEXT NOT NULL DEFAULT '';
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS color TEXT;
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS is_fiber BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS connection_type TEXT;
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS strand_count INTEGER;
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS length_meters DOUBLE PRECISION;
